
all:
	python3 pacman.py

tinyMazeSearch:
	python pacman.py -l tinyMaze -p SearchAgent -a fn=tinyMazeSearch	

dfs:
	python pacman.py -l tinyMaze -p SearchAgent -a fn=dfs

dfsMedio:
	python pacman.py -l mediumMaze -p SearchAgent -a fn=dfs	
	
dfsGrande:
	python pacman.py -l bigMaze -p SearchAgent -a fn=dfs	
