
all:
	python3 pacman.py

tinyMazeSearch:
	python3 pacman.py -l tinyMaze -p SearchAgent -a fn=tinyMazeSearch	

dfs:
	python3 pacman.py -l tinyMaze -p SearchAgent -a fn=dfs

dfsMedio:
	python3 pacman.py -l mediumMaze -p SearchAgent -a fn=dfs	
	
dfsGrande:
	python3 pacman.py -l bigMaze -p SearchAgent -a fn=dfs	

bfs:
	python3 pacman.py -l tinyMaze -p SearchAgent -a fn=bfs

bfsMedio:
	python3 pacman.py -l mediumMaze -p SearchAgent -a fn=bfs	
	
bfsGrande:
	python3 pacman.py -l bigMaze -p SearchAgent -a fn=bfs	

ucs:
	python3 pacman.py -l tinyMaze -p SearchAgent -a fn=ucs

ucsMedio:
	python3 pacman.py -l mediumMaze -p SearchAgent -a fn=ucs	
	
ucsGrande:
	python3 pacman.py -l bigMaze -p SearchAgent -a fn=ucs	

sempreDireita:
	python3 pacman.py -l mediumDottedMaze -p StayEastSearchAgent

sempreEsquerda:
	python3 pacman.py -l mediumDottedMaze -p StayWestSearchAgent

assustadorDireita:
	python3 pacman.py -l mediumScaryMaze -p StayEastSearchAgent

assustadorEsquerda:
	python3 pacman.py -l mediumScaryMaze -p StayWestSearchAgent

direitaPontos:
	python3 pacman.py -l mediumDottedMaze -p StayEastSearchAgent

esquerdaPontos:
	python3 pacman.py -l mediumDottedMaze -p StayWestSearchAgent
